server:
  port: 20002
spring:
  application:
    name: omega-zipkin
management:
  metrics:
    web:
      server:
        auto-time-requests: false
logging:
  file: ${user.home}/data/logs/${spring.application.name}
  level:
    root: debug