eureka:
  instance:
    prefer-ip-address: true
    instance-id: omega-zipkin:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://omega-eureka:22001/eureka/,http://omega-eureka:22002/eureka/