server:
  port: 8081
logging:
  file: ${user.home}/data/logs/${spring.application.name}
  level:
    root: debug
spring:
  application:
    name: omega-boot-example
  #  zipkin:
  #    enabled: true
  #    base-url: http://localhost:20002/
  #    locator:
  #      discovery:
  #        enabled: true
  #  sleuth:
  #    sampler:
  #      probability: 1
  datasource:
    url: jdbc:mysql://localhost:3306/llh_test_db
    username: root
    password: 815711
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    prefer-ip-address: true
    instance-id: omega-example:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://omega-eureka:22001/eureka/,http://omega-eureka:22002/eureka/

