server:
  port: 8082
logging:
  file: ${user.home}/data/logs/${spring.application.name}
  level:
    root: debug
spring:
  application:
    name: omega-agg-platform
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 815711
    url: jdbc:mysql://omega-eureka:3306/omega_web?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: omega-example:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://omega-eureka:22001/eureka/,http://omega-eureka:22002/eureka/


