server:
  port: 8082
logging:
  file: ${user.home}/data/logs/${spring.application.name}
  level:
    root: debug
spring:
  application:
    name: omega-agg-platform
eureka:
  instance:
    prefer-ip-address: true
    instance-id: omega-example:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://omega-eureka:22001/eureka/,http://omega-eureka:22002/eureka/